#!/bin/bash
#
# ClovaLink Installer
# One-line install: curl -fsSL https://raw.githubusercontent.com/ClovaLink/ClovaLink/main/install.sh | bash
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Print banner
echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}                                                               ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   ${BOLD}🍀 ClovaLink Installer${NC}                                      ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   Enterprise File Management Made Simple                      ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}                                                               ${CYAN}║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to generate random string
generate_secret() {
    if command -v openssl &> /dev/null; then
        openssl rand -base64 32 | tr -d '/+=' | head -c 32
    elif [ -f /dev/urandom ]; then
        cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32
    else
        date +%s%N | sha256sum | head -c 32
    fi
}

# Function to check command exists
check_command() {
    if ! command -v "$1" &> /dev/null; then
        return 1
    fi
    return 0
}

# Function to read input (works when piped to bash)
read_input() {
    local prompt="$1"
    local var_name="$2"
    local default="$3"
    
    echo -en "$prompt"
    if [ -t 0 ]; then
        # stdin is a terminal, read normally
        read -r input
    else
        # stdin is a pipe, read from /dev/tty
        read -r input < /dev/tty
    fi
    
    if [ -n "$input" ]; then
        eval "$var_name=\"$input\""
    elif [ -n "$default" ]; then
        eval "$var_name=\"$default\""
    fi
}

# Step 1: Check Docker
echo -e "${BLUE}[1/5]${NC} Checking Docker installation..."

if check_command docker; then
    DOCKER_VERSION=$(docker --version 2>/dev/null | cut -d' ' -f3 | cut -d',' -f1)
    echo -e "  ${GREEN}✓${NC} Docker ${DOCKER_VERSION} is installed"
elif check_command podman; then
    PODMAN_VERSION=$(podman --version 2>/dev/null | cut -d' ' -f3)
    echo -e "  ${GREEN}✓${NC} Podman ${PODMAN_VERSION} is installed"
    DOCKER_CMD="podman"
    COMPOSE_CMD="podman-compose"
else
    echo -e "  ${RED}✗${NC} Docker is not installed"
    echo ""
    echo -e "${YELLOW}Please install Docker first:${NC}"
    echo ""
    echo "  Linux:   curl -fsSL https://get.docker.com | sh"
    echo "  Mac:     brew install --cask docker"
    echo "  Windows: Download from https://docker.com/products/docker-desktop"
    echo ""
    exit 1
fi

# Set compose command
if [ -z "$COMPOSE_CMD" ]; then
    if docker compose version &> /dev/null; then
        COMPOSE_CMD="docker compose"
    elif check_command docker-compose; then
        COMPOSE_CMD="docker-compose"
    else
        echo -e "  ${RED}✗${NC} Docker Compose is not available"
        echo "  Please install Docker Compose: https://docs.docker.com/compose/install/"
        exit 1
    fi
fi
echo -e "  ${GREEN}✓${NC} Using: ${COMPOSE_CMD}"

# Step 2: Create directory
echo ""
echo -e "${BLUE}[2/5]${NC} Setting up installation directory..."

INSTALL_DIR="${CLOVALINK_DIR:-$HOME/clovalink}"

# Ask for installation directory
echo -e "  Where would you like to install ClovaLink?"
echo -e "  ${CYAN}Press Enter for default: ${INSTALL_DIR}${NC}"
read_input "  Directory: " USER_DIR ""
if [ -n "$USER_DIR" ]; then
    INSTALL_DIR="$USER_DIR"
fi

# Create directory
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
echo -e "  ${GREEN}✓${NC} Created: $INSTALL_DIR"

# Step 3: Download files
echo ""
echo -e "${BLUE}[3/5]${NC} Downloading configuration files..."

REPO_URL="https://raw.githubusercontent.com/ClovaLink/ClovaLink/main/infra"

curl -fsSL "$REPO_URL/compose.yml" -o compose.yml
echo -e "  ${GREEN}✓${NC} Downloaded compose.yml"

curl -fsSL "$REPO_URL/.env.example" -o .env.example 2>/dev/null || true
echo -e "  ${GREEN}✓${NC} Downloaded .env.example"

# Step 4: Configure environment
echo ""
echo -e "${BLUE}[4/5]${NC} Configuring your installation..."

# Generate secrets
JWT_SECRET=$(generate_secret)
POSTGRES_PASSWORD=$(generate_secret)

echo -e "  ${GREEN}✓${NC} Generated secure JWT secret"
echo -e "  ${GREEN}✓${NC} Generated secure database password"

# Ask for ports
echo ""
echo -e "  ${CYAN}Web interface port (default: 8080):${NC}"
read_input "  Port: " WEB_PORT "8080"

echo -e "  ${CYAN}API port (default: 3000):${NC}"
read_input "  Port: " API_PORT "3000"

# Create .env file
{
    echo "# ClovaLink Configuration"
    echo "# Generated by installer on $(date)"
    echo ""
    echo "# Security - These were auto-generated, keep them secret!"
    echo "JWT_SECRET=${JWT_SECRET}"
    echo ""
    echo "# Database"
    echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    echo "DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/clovalink"
    echo ""
    echo "# Redis"
    echo "REDIS_URL=redis://redis:6379"
    echo ""
    echo "# Storage (local by default, configure S3 for production)"
    echo "STORAGE_TYPE=local"
    echo ""
    echo "# Optional: S3/Backblaze B2/Wasabi configuration"
    echo "# S3_ENDPOINT=https://s3.us-west-002.backblazeb2.com"
    echo "# S3_BUCKET=your-bucket-name"
    echo "# S3_REGION=us-west-002"
    echo "# S3_ACCESS_KEY=your-access-key"
    echo "# S3_SECRET_KEY=your-secret-key"
    echo ""
    echo "# Environment"
    echo "ENVIRONMENT=production"
    echo "RUST_LOG=info"
} > .env

echo -e "  ${GREEN}✓${NC} Created .env configuration"

# Update compose.yml ports if changed
if [ "$WEB_PORT" != "8080" ]; then
    sed -i.bak "s/8080:80/${WEB_PORT}:80/g" compose.yml 2>/dev/null || \
    sed -i '' "s/8080:80/${WEB_PORT}:80/g" compose.yml
fi
if [ "$API_PORT" != "3000" ]; then
    sed -i.bak "s/3000:3000/${API_PORT}:3000/g" compose.yml 2>/dev/null || \
    sed -i '' "s/3000:3000/${API_PORT}:3000/g" compose.yml
fi
rm -f compose.yml.bak 2>/dev/null

# Step 5: Start services
echo ""
echo -e "${BLUE}[5/5]${NC} Starting ClovaLink..."
echo ""
echo -e "  ${YELLOW}This may take a few minutes on first run...${NC}"
echo ""

$COMPOSE_CMD up -d

# Wait for services to be ready
echo ""
echo -e "  Waiting for services to start..."
sleep 5

# Check if services are running
if $COMPOSE_CMD ps | grep -q "Up\|running"; then
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║${NC}                                                               ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}   ${BOLD}🎉 ClovaLink is now running!${NC}                                ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}                                                               ${GREEN}║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  ${BOLD}Web Interface:${NC}  ${CYAN}http://localhost:${WEB_PORT}${NC}"
    echo -e "  ${BOLD}API Endpoint:${NC}   ${CYAN}http://localhost:${API_PORT}${NC}"
    echo ""
    echo -e "  ${BOLD}Default Login:${NC}"
    echo -e "    Email:    ${CYAN}superadmin@clovalink.com${NC}"
    echo -e "    Password: ${CYAN}password123${NC}"
    echo ""
    echo -e "  ${YELLOW}⚠️  Change the default password immediately!${NC}"
    echo ""
    echo -e "  ${BOLD}Useful Commands:${NC}"
    echo -e "    View logs:    ${CYAN}cd $INSTALL_DIR && $COMPOSE_CMD logs -f${NC}"
    echo -e "    Stop:         ${CYAN}cd $INSTALL_DIR && $COMPOSE_CMD down${NC}"
    echo -e "    Update:       ${CYAN}cd $INSTALL_DIR && $COMPOSE_CMD pull && $COMPOSE_CMD up -d${NC}"
    echo ""
else
    echo ""
    echo -e "${RED}Something went wrong. Check the logs:${NC}"
    echo -e "  cd $INSTALL_DIR && $COMPOSE_CMD logs"
    exit 1
fi
